apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: yuragranovsky/logs-bugs-reporter_logs-bugs-config:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: logs-bugs-config
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
  - port: 8888
    targetPort: 8888

