apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      
      containers:
      - name: discovery-server
        image: yuragranovsky/logs-bugs-reporter_discovery-server:0.0.1
        resources:
          requests:
            memory: "132Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: ClusterIP
  selector:
    app: discovery-server
  ports:
  - port: 8761
    targetPort: 8761

