apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-notifier-deployment
spec:
  selector:
    matchLabels:
      app: email-notifier
  template:
    metadata:
      labels:
        app: email-notifier
    spec:
      containers:
      - name: email-notifier
        image: yuragranovsky/logs-bugs-reporter_email-notifier:0.0.1
        resources:
          requests:
            memory: "132Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: KAFKA_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: logs-bugs-configmap
                key: kafka-password
              
